//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenisovArt_Kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedService
    {
        public int ServiceID { get; set; }
        public int VisitListID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public int OrderServiceID { get; set; }
    
        public virtual CatalogOfService CatalogOfService { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual VisitList VisitList { get; set; }
    }
}
